### PR TITLE
Show/hide password feature added

### PR DESCRIPTION
**Pull request by Siddhesh777**
**Issue reference:**
Issue #10 

**Proposed changes:**
Added a button which toggles for showing/hiding password

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please specify)
- [ ] This change requires a documentation update

**Checklist:**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

**Additional info (if any):**
issue1

issue2

### CODE REVIEW

**Comment by Siddhesh777** [comment]
Hey @varunKT001 
I think I have all those changes you had suggested before.
I created a new pull req just to handle that conflict.
sorry for inconvenience :(

**Comment by varunKT001** [comment]
@Siddhesh777 
More changes needed:

- Give the border-radius for the password fields (same as given in the email fields)
- You have removed the loading button implementation. You removed the import `../../Button` and also changed the `<Button>` component to normal `<button>` in the `Login` and `Register` pages. Don't make changes to any code that you are not working on. You can look at the current code and make the changes.

If you have any doubts, ping me on discord 👍

**Comment by Siddhesh777** [comment]
hey @varunKT001 😅
Gave the radius for the password fields and also corrected the Button.
All the best for your exams!! have a blast😅

**Comment by varunKT001** [comment]
@Siddhesh777 
I'm sorry for the delay 😅 
I have tested it, works fine, and also the UI looks very good. Nice work 👍 

Thanks for your contribution 🎉

**Comment by Siddhesh777** [comment]
Hey @varunKT001 😅
I think you forgot to add gssoc label

**Comment by varunKT001** [comment]
@Siddhesh777 Thanks for reminding me 😅
Added 👍

**Comment by Siddhesh777** [comment]
@varunKT001 
Can I know why the labels have been removed?

**Comment by varunKT001** [comment]
@Siddhesh777 
There were multiple Pull Requests on the same topic `Toggle Password/ Show-Hide password`. That's why I was told to remove the labels for the Pull Requests 😞

**Comment by Siddhesh777** [comment]
@varunKT001 
It was completely implemented by me.
Why the plagiarized tag is there?🙂
No matter how many pull request were there if I had been allotted an issue by the mentor and I had worked on it,How can someone ask you to remove the labels?🙂
If there were multiple pull request then I think the issue itself should not have been allotted.🙂

**Comment by varunKT001** [comment]
@Siddhesh777 
I'll get this figured out, just wait for some time.

**Comment by varunKT001** [comment]
@Siddhesh777
I'm sorry for the trouble 😅.
I'm adding the labels again 👍

**Comment by Siddhesh777** [comment]
No problem @varunKT001 
And thank you very much for the help !😅

**Pull request merged**
