### PR TITLE
Add Better Footer

### PR DESCRIPTION
**Pull request by Shubham29012001**
#8

Add Better Responsive Footer

UI/UX Change

- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by varunKT001** [comment]
I just removed some dependencies from package.json
Update your fork and the merge conflicts will be removed 👍

**Comment by Shubham29012001** [comment]
Hey @varunKT001, when I am clicking on Fetch Upstream, it is prompting me to open a pull request in it. Can you assist me with it?

**Comment by varunKT001** [comment]
Okay, then you just download the new `package.json` and `package-lock.json` file and add them to your local clone 🙂
This may sound too naive, but believe me, you wouldn't want to go the git way 😅

**Comment by Shubham29012001** [comment]
Hey @varunKT001. It worked. Can you please checkout the footer section?

**Comment by varunKT001** [comment]
Some more changes:
- remove the white background color from icons (just remove the background-color property)
- for icons, you have already given font size in the `constant.js`, so remove the width and height properties of SVG from `styles.js`
- instead of using `<hr>`, use a div with className of `underline`. 
```
.underline {
    width: 95%;
    height: 1px;
    margin-bottom: 1rem;
    background: var(--clr-grey-7);
}
```
- remove the services link, since there is no page for that (didn't notice, sorry 😅)
- for the contact link, add an if condition, and instead of `<Link>`, use `<a>` with `href='mailto:tiwarivarun819.vt33.vt@gmail.com'`
- for the footer links, instead of `key={id}` you have written `className={id}` 🙂 fix that
- and the last, in the `constant.js`, change the color of github icon to white

Do the changes and then tag me here 👍

**Comment by Shubham29012001** [comment]
Hey @varunKT001, I have applied all the mentioned changes in the footer.

**Comment by varunKT001** [comment]
Nice work 👍
Thanks for your contribution @Shubham29012001 🚀

We also added the backend and the admin panel to the GSSoC22 project list, you can find links to them from the readme. I'll happy to see you working on those projects too 😄

**Pull request merged**
