### PR TITLE
Confirm Password field addded in registration page

### PR DESCRIPTION
**Pull request by Siddhesh777**
**Issue reference:**
Earlier there was no field for confirm password while registering new user

**Proposed changes:**
I added a field for confirming password and if they both don't match it gives an error.

**Type of change:**

- [x] Enhancement

**Checklist:**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

**Additional info (if any):**

issue solved

### CODE REVIEW

**Comment by varunKT001** [comment]
Hey @Siddhesh777 👋,

Some improvements needed:

- Why did you delete the `.env.sample`? That file was not to be deleted. Don't remove that file.
- Use some good variable and function names. For eg: change `cpassword` and `setcpassword` to `confirmPassword` and `setConfirmPassword`. 
- In the setup guide, I mentioned that you must have `prettier` installed to format the code. If you are using `VS Code`, you can install the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode). Or, if you are using any other code editor, check the [prettier docs](https://prettier.io/docs/en/editors.html) to learn how to integrate `prettier` to your code editor. 
- Format the changed files using `prettier` before committing and pushing your code.

After making the changes, fill the checklist in the pull request and tag me here 👍

**Comment by Siddhesh777** [comment]
Hey @varunKT001 👋
Done with the improvements mentioned.
Kindly check and merge.

**Comment by varunKT001** [comment]
One small change though 😅
Change the error message for non-matching passwords to:
`Passwords didn't match`
Do this small change, and I'll merge 👍 

Also, please make a habit of writing good commit messages, it will help me/mentors to get a brief idea about what was changed without the need to go and check the differences.

**Comment by Siddhesh777** [comment]
@varunKT001 
Changed the error message.
Yes, I am making a habit of writing good commit messages😅
Thank You.

**Comment by varunKT001** [comment]
> Changed the error message.

Great work @Siddhesh777 🚀

> Yes, I am making a habit of writing good commit messages😅

These small habits that you'll during these 3 months of GSSoC'22, will surely help you in the future 😄

Thanks for your contribution 🎉

**Comment by varunKT001** [comment]
@Siddhesh777 Sure, if you ever need help, just ping me on the TomperWear discord channel, I'll be happy to help 😄

**Pull request merged**
