### PR TITLE
Loading spinner when button is disabled

### PR DESCRIPTION
**Pull request by sagnik2001**
**Issue reference:**
Loading spinner when the button is disabled 

**Proposed changes:**
Added spinner when an API request is made or when the button is disabled.

**Type of change:**

- [ ] New feature (non-breaking change which adds functionality)

**Checklist:**

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

**Additional info (if any):**

I have made the changes in the components which I found if any left out I will do the desire changes

### CODE REVIEW

**Comment by varunKT001** [comment]
@sagnik2001 There is nothing wrong with your implementation, but it creates some issues: 
- You have to make a check for the loading state, whenever you use a button that calls an API.
- The loading button is bigger in size than the non-loading one. It causes a sudden scroll on the page, which looks odd 😕

What I wanted you to do, was to create an `src/components/Button` component that will accept all the props: 
```
const Button = ({ disabled, children, ...rest }) => {
  if (disabled) {
    return (
      <button disabled={disabled} {...rest}>
        <Icon />
      </button>
    );
  }

  return (
    <button {...rest}>
      {Children}
    </button>
  );
};
```
something like this ⬆️ 

After doing so, you can replace all the instances of `<button>` with this component `<Button>` where you can give all the props just like you did in the normal `button`

For the label, you can make a check manually
```
<label>
  { loading ? <Icon/> : 'text' }
</label>
```

I hope you got my point 👍

**Comment by varunKT001** [comment]
@sagnik2001 There is nothing wrong with your implementation, but it creates some issues: 
- You have to make a check for the loading state, whenever you use a button that calls an API.
- The loading button is bigger in size than the non-loading one. It causes a sudden scroll on the page, which looks odd 😕

What I wanted you to do, was to create an `src/components/Button` component that will accept all the props: 
```javascript
const Button = ({ disabled, children, ...rest }) => {
  return (
    <button disabled={disabled} {...rest}>
      {disabled ? <Icon /> : children}
    </button>
  );
};
```
something like this ⬆️ 

After doing so, you can replace all the instances of `<button>` with this component `<Button>` where you can give all the props just like you did in the normal `button`

For the label, you can make a check manually
```jsx
<label>
  { loading ? <Icon/> : 'text' }
</label>
```

I hope you got my point 👍

**Comment by sagnik2001** [comment]
Okay,making the changes

**Comment by sagnik2001** [comment]
Hey @varunKT001, check if this is what you want??

**Comment by varunKT001** [comment]
@sagnik2001 Yeah, that's what I wanted, but you have to do some more changes 😅 

- Use normal buttons for the google sign in/sign up (there is an issue with that, we'll into it later)
- For the label on the profile page, remove the check and make it normal. It's making the button shrink. Didn't notice it at first, really sorry for that 😓 

```jsx
<label>upload image</label>
```

- Somewhere in the profile page, you passed the disabled prop two times 🙂 fix that (also make sure to always check the console warnings before making a commit).
- Rename the button component name from `LoadingButton` to `Button`, since it can be used as a normal button.\
- In the loading icon component, add a width of `1.025rem` (I tested it, works fine)

```jsx
<svg style={{ ... , width: '1.025rem' }}>
  ...
</svg>
```

- Remove the extra lines that you have put in the jsx in all the changed files and make sure to format all files.
- There are a few more buttons that make API calls: `review button` and `feedback button`. Do the change for them too.

For now, do these changes 👍

**Comment by sagnik2001** [comment]
Check it @varunKT001, is it okay now??

**Comment by varunKT001** [comment]
> In the loading icon component, add a width of 1.025rem (I tested it, works fine)

Remove the width and height, otherwise, there is no sense of putting `width: '1.025rem'`
image
remove these two lines ⬆️ 

> Use normal buttons for the google sign in/sign up (there is an issue with that, we'll into it later)

You didn't do this change. 
image
Make these normal buttons `<button>`, in both the login and register pages.

> also make sure to always check the console warnings before making a commit

Still, there is a warning
image
Remove the import `Icon`, since we are not using it.

**Comment by sagnik2001** [comment]
Hey @varunKT00,check it hope it's fine now

**Comment by varunKT001** [comment]
Looks good now 👍 

Thanks for contributing @sagnik2001 🚀

**Pull request merged**
