### PR TITLE
Footer css

### PR DESCRIPTION
**Pull request by sagnik2001**
**Issue reference:**
 Fixing Small Css Issue of Footer

**Proposed changes:**

- Change the icon color of all footer icons to var(--clr-primary-5)
- Change the text color of the footer links and the bottom-most text to var(--clr-grey-6)
- Apply hover effect on the footer links: Change text color to var(--clr-primary-5) on hover

**Type of change:**

- [ ] New feature (non-breaking change which adds functionality)

**Checklist:**

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by varunKT001** [comment]
@sagnik2001 Please use prettier and format the files you changed. you can download the extension for it if you are using `VS Code`

Other than that, everything looks fine.

**Comment by sagnik2001** [comment]
Hey @varunKT001 I used the prettier and it adds a space between the files(footer -styles.js) will it be ok??

**Comment by varunKT001** [comment]
Yes, totally fine. It's following the prettier configuration file `.prettierrc` so no issues 👍

**Comment by sagnik2001** [comment]
Done

**Comment by varunKT001** [comment]
You have also formatted the `constants.js` file, right?

**Comment by sagnik2001** [comment]
yes its already been using prettier so no additional changes

**Comment by varunKT001** [comment]
Okay then 👍

Thanks for contributing 🎉

**Pull request merged**
