### PR TITLE
toggling password visibility

### PR DESCRIPTION
**Pull request by Siddhesh777**
**Issue reference:**
#50 

**Proposed changes:**
changes in [/pages/ProfilePage](url)
Added the functionality which toggles the visibility of passwords when we user is changing the password in [/profile](url)

**Type of change:**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please specify)
- [ ] This change requires a documentation update

**Checklist:**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

**Additional info (if any):**

### CODE REVIEW

**Comment by varunKT001** [comment]
@Siddhesh777 
Before starting to work on any new change, make sure that your forked repository is updated. As I'm checking your changes, I saw that the loader was not working and that's because you didn't do the `fetch and merge` after your previous pull request was merged. 
The current pull request is fine, just update your forked repository and tag me here 👍

**Comment by Siddhesh777** [comment]
hey @varunKT001 
I didn't get what should I do actually.
Still I had clicked on fetch and merge option of my branch.
Is it fine?or should I do something else?

**Comment by varunKT001** [comment]
@Siddhesh777 
Yes, that's what I meant. Also, before starting to work on any new issue, make sure you do this 👍 

Thanks for contributing 🚀

**Comment by Siddhesh777** [comment]
@varunKT001 here too you removed the labels..:(
What happened?

**Pull request merged**
