### PR TITLE
Search bar bug

### PR DESCRIPTION
**Pull request by sagnik2001**
### Issue reference:

Search Bug Filter issue resolved. #11 

### Proposed changes:

The Search Bar was previously working if you type all lower case which is not the expected behavior. I have fixed 2 issues:

- Filter products irrespective of case.

- Filter products if the search string is a substring of the product's name.

### Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Screenshot from 2022-03-03 10-14-00

Current working behavior.

### CODE REVIEW

**Comment by varunKT001** [comment]
Why did you update the react-scripts dependencies 🤔 Is there any problem starting the dev-server?

I can see you added some new lines to the components and files. Now two things:
- You should follow the existing code style.
- Why are you doing changes in the files where it is not required? The files `src/components/Contact/index.js` and `src/components/context/filter_context.js` have nothing to do with the actual filter logic. The only file that was meant to be changed was the `filter_reducer.js`
- Also try to comment only on the parts which are hard to understand. `Array.includes()` is very common and doesn't need to be commented 👍

Now,
- Remove the extra lines in the above files I mentioned.
- Remove the comment you added in the reducer.
- Also, If there is a problem with the dependencies, create a new issue. For now, just revert that 👍.

**Comment by sagnik2001** [comment]
Okay, I do the required changes I did update the react-scripts because in my local machine it was not working. Ok, I do as instructed.

**Comment by varunKT001** [comment]
What was the issue?

**Comment by sagnik2001** [comment]
The local server was failing to run.

**Comment by varunKT001** [comment]
Wait then, let me check.

**Comment by sagnik2001** [comment]
Should I make the changes that you asked for and again commit ??

**Comment by varunKT001** [comment]
wait for now, let me check the issue 👍

**Comment by varunKT001** [comment]
Hmm, since react-scripts@5 is not causing any breaking change, we can have that, no need to change.
Also I have tested the PR, works fine 👍
Just make the other changes 👍

**Comment by sagnik2001** [comment]
Okay

**Comment by sagnik2001** [comment]
Hey, I have made the commits. Have a look and thanks for the opportunity

**Comment by varunKT001** [comment]
@sagnik2001 comments bhi to hatana tha 🙂

**Comment by sagnik2001** [comment]
Done, sorry missed out that previously thanks

**Comment by varunKT001** [comment]
Great 🎉, Thanks for your contribution @sagnik2001
Stay tuned, more issues will be added. Also, if you find anything that could be improved, create an issue 👍
Also, the backend and the admin panel will soon be added, I'll be happy to see you contributing to them too 😅
You can join the discord channel also (finally we have it now 😅)

Happy contributing 🥳

**Pull request merged**
