### PR TITLE
Add ScrollToTop button component

### PR DESCRIPTION
**Pull request by Nikhil-Sharma1**
**Issue reference:** No Scroll To Top button in any page

**Proposed changes:** Add scroll to top button

**Type of change:** Adding scroll to top functionality

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

**Checklist:**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

**Additional info (if any):**
I have added the Scroll-to-top button on every page. Since the height of the About page is less, so there is no need of scroll-to-top button there, hence the scroll-to-top button is not accessible there. If we include more data in that page and the height of that page is increasing in future, then the scroll-to-top button is appearing automatically after some scroll down. In other pages, it works fine. I have add transition effect on hover also. Please merge it with the main project.

I just add ScrollToTop folder in component folder to mantain the format and impoert that file file in app.js . So the format of the project does not change a bit.

Screenshot
1) Initially button is not visible
Screenshot (302)
2) After some scroll down, button is visible
Screenshot (307)
3) Transition effect on hover
Screenshot (308)

### CODE REVIEW

**Comment by varunKT001** [comment]
**Some improvements need**

- You have made some changes in `package.json`. You changed the `build scripts`. Your change will make the build process fail. Remove all the changes done in the `package.json`.
- The button doesn't look good. You had to use the color variables I made in the `src/index.css`.
- You have created an event listener directly in the component. This is the worst way you can make event listeners. What will happen is, on every render, the component will get recreated. On every recreation of the component, new event listeners will get created. Therefore the thread will get loaded with tons of similar event listeners and the app will crash. For this you have to use `useEffect()`

```js
useEffect(() =>{
  window.addEventListener('scroll', toggleVisible);
  return () => window.removeEventListener('scroll', toggleVisible);
}, [])
```

Make these changes and tag me here 👍

**Comment by Nikhil-Sharma1** [comment]
Thank you for giving me one more chance

**Comment by varunKT001** [comment]
@Nikhil-Sharma1 
It works fine, but you still need to make some changes:

- Improve the UI. 
  - Instead of a circle, use a square with some border-radius. 
  - The icon is transparent so we can see things moving through it. Use some containers as a background.
  - Don't put any hover effect.
- You should follow the code style. Remove the unnecessary blank lines that you have put. Only give one new line between each function.
- If you are using `vs-code`, download the `prettier` extension, and from `vs-code` settings, enable `format on save`. If you are using some other editor, go to the [prettier docs](https://prettier.io/docs/en/editors.html) to see how to integrate `prettier` with your editor. Make sure you format the code properly.

**Comment by Nikhil-Sharma1** [comment]
ok sir

**Comment by varunKT001** [comment]
@Nikhil-Sharma1 
No need to call `sir` bro 😅
Also, if you need any help, just ping me on the discord server 👍

**Comment by Nikhil-Sharma1** [comment]
ok bro😂

**Comment by Nikhil-Sharma1** [comment]
1)use transparent icon
2)change button shape
Screenshot
Screenshot (310)
Screenshot (311)

**Comment by varunKT001** [comment]
@Nikhil-Sharma1 
First of all, really sorry for the delay, I was busy somewhere 😞

Now, you didn't do all the changes I asked for:

> The icon is transparent so we can see things moving through it. Use some containers as a background.

I can still see the background moving from the button. Give the button background some primary color (you can try `clr-primary-5`). Also, make the icon color white. That will solve the problem.

> Don't put any hover effect.

Remove the hover effect. It doesn't look good 😕

And finally the most important step, format all the files you change using `prettier` (code should not look ugly 🙂)

Do these changes and tag me here 👍

**Pull request closed without merging**
