### PR TITLE
Issue 39 Fixed

### PR DESCRIPTION
**Pull request by mani200307**
**Issue reference:**
In reference to issue https://github.com/varunKT001/tomper-wear-ecommerce/issues/39

**Proposed changes:**
Enhancement : Navigation button to move to the top of the page

**Type of change:**
Added navigation button to move to the top of the page

**Checklist:**
 My code follows the style guidelines of this project
 I have performed a self-review of my own code
 I have commented my code, particularly in hard-to-understand areas
 I have made corresponding changes to the documentation
 My changes generate no new warnings
Additional info (if any):

### CODE REVIEW

**Comment by varunKT001** [comment]
@mani200307 The look of the button doesn't match the website's theme. You might want to use an arrow icon, along with some reduced border-radius and primary brown color (you can find the list of colors in the global CSS file). Also, the button doesn't fit well on small-screen devices, so please look into that also.

**Comment by mani200307** [comment]
Sure I'll modify.

**Comment by mani200307** [comment]
image

@varunKT001, Is this style fine for the scroll to top button? Any changes required?

**Comment by varunKT001** [comment]
@mani200307 Keep it square with some border-radius. Also, give some padding to the arrow doesn't look congested inside the shape.

**Comment by mani200307** [comment]
Yeah, I made the changes and did commit. Now, that button is responsive too.

**Comment by mani200307** [comment]
Thanks @varunKT001, Now, I made the changes and did commit. Now, that button is responsive too.

**Comment by varunKT001** [comment]
@mani200307 I've left some reviews, please look into those.

**Pull request closed without merging**
