### PR TITLE
Existing password check added before changing password

### PR DESCRIPTION
**Pull request by Siddhesh777**
**Issue reference:** #41 

**Proposed changes:**
changed the /src/pages/profilePage/index.js & /src/context/user_context.js
I have made the functionality to verify the existing password before letting the user to change the password.

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please specify)
- [ ] This change requires a documentation update

**Checklist:**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

**Additional info (if any):**

### CODE REVIEW

**Comment by Siddhesh777** [comment]
hello @varunKT001 😅
are those changes fine?

**Comment by varunKT001** [comment]
@Siddhesh777 
Sorry for the delay 😅 

I just checked your pull request. It's working fine, but still, some changes are needed:

- Since in the project, almost everywhere, the async-await syntax is used. So I would suggest you re-write the `handleSubmitPassword` function using the async-await syntax. It just looks cleaner and less confusing.
- Once again reminding, do format the files you changed, using prettier:
image
You have added these two lines for no reason 🙂 If you had formatted it using prettier, these unnecessary lines would have been automatically removed.

Make these changes and tag me here 👍 
If you need any help, ping me on the discord channel 👍

**Comment by Siddhesh777** [comment]
hey @varunKT001 
I have made suggested changes.
kindly check.

**Comment by varunKT001** [comment]
@Siddhesh777 
You didn't re-wrote all the code to async-await, there's more left 🙂  
image
Don't worry about the `catch` block. Just return:

```js
toast.error(`Error: ${error.message}`)
```

It will catch all the errors 👍

Also two more things:

- Start the loading before the `reauthenticateUser` function call.
- End the loading after the `try-catch` block.
image
You have removed it 🙂 

Please look into all those things. Also, don't be in hurry, take your time thinking about what should be the correct flow of the code. Check everything twice before making a pull request. Don't write code just to get your pull request merged. It's also a **pain** to me to tell you about these small things **every time**. You only think why will I check things manually if I can see everything already messed up in **Github** itself 🙂

**Comment by Siddhesh777** [comment]
@varunKT001 
Sorry for the inconvenience.
I am actually beginner in Web-development so I think I mess up the things.
I have made suggested changes, you can check them.
I would like to say I am learning so much from the program gssoc'22.
Thanks!

**Comment by varunKT001** [comment]
@Siddhesh777 
No one is an expert 👍 
I am just telling you, just look at all your changes twice and make sure that you have done everything that you have been told. Don't be in a hurry 👍 

Also, I said directly convert the other part to async-await. No need to use another `try-catch` block. Since firebase's error will always contain a `message` property, the error will get handled properly in one `try-catch` block only.  

```js
function handleSubmitPassword() {
    ...
    ...
    setLoading(true);
    try {
      // eslint-disable-next-line
      const response_2 = await reauthenticateUser(exisitingPassword);
      if (newPassword.length < 6) {
        return toast.error('Password should be atleast 6 characters');
      }
      if (newPassword !== confirmNewPassword) {
        return toast.error('Passwords do not match');
      }
      const response_3 = await updateUserProfilePassword(confirmNewPassword);
      toast.success('Profile password changed successfully');
    } catch (error) {
      toast.error('Current password do not match');
    }
    setLoading(false);
};
```

Also, don't use `return` while writing the `toast.error...`, because if we return from the function, `setLoading(false)` won't execute and will cause a memory leak warning.

**Comment by Siddhesh777** [comment]
@varunKT001 
I have done the changes 🙂
Please check them.
Even if it needs more corrections, let me know.
I am seriously thankful to you😄 ,I am learning so much from this project.

**Comment by varunKT001** [comment]
@Siddhesh777 
Checked it, everything works fine 👍 

One last change, as I said in a previous comment:
In the catch block, instead of hardcoding the error message, use the following:

```js
toast.error(`Error: ${error.message}`)
```

So that, we can see the original firebase error 👍 

Do this last change 👍

**Comment by Siddhesh777** [comment]
hey @varunKT001 😅
Did it !😅

**Comment by varunKT001** [comment]
@Siddhesh777 
It's good to merge now 😄 

Thanks for having such patience. I'm happy to see you take all my suggestions calmly. I have seen many peoples (while I was at your stage) get frustrated if asked to make more changes again and again 😕 

Thanks for contributing 🚀

**Pull request merged**
